sudo: required
language: node_js
node_js: '12'

matrix:
  include:
    - os: osx
      osx_image: xcode10
      addons:
        chrome: stable
      before_install:
        - openssl aes-256-cbc -K $encrypted_527645209bb0_key -iv $encrypted_527645209bb0_iv -in build/mac-cert.tar.enc -out mac-cert.tar -d
        - tar xvf mac-cert.tar

    - os: linux
      dist: xenial
      language: generic
      services:
        - docker
#      before_install:
#        - sudo snap install snapcraft --classic
#        - export CHROME_BIN=chromium-browser
#        - export DISPLAY=:99.0
#        - sh -e /etc/init.d/xvfb start

addons:
  ssh_known_hosts:
    - the-front-end.de
    - frs.sourceforge.net
  apt:
    packages:
      - sshpass

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

script:
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      PUB=always
    else
      PUB=never
    fi
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      echo '____RUNNING DOCKER____'
      bash ${TRAVIS_BUILD_DIR}/build/docker/run-linux-win.sh ${PUB}
    else
      yarn install && yarn add 7zip-bin-mac
      yarn run buildAllElectron:noTests
      travis_wait 30 yarn dist:mac:dl -p $PUB
    fi

# NOTE: disabled until next release of electron builder
#      if [ -n "$TRAVIS_TAG" ]; then
#        yarn dist:mac:mas
#      fi


deploy:
  # Snap Deployment
  - on:
      condition: $TRAVIS_OS_NAME = linux
      tags: false
      branch: master
    provider: snap
    snap: ./app-builds/*.snap
    channel: edge
    skip_cleanup: true
    # we use edge because of this: https://travis-ci.community/t/snap-deployment-stopped-working-out-of-nowhere/6908/2
    edge: true
  - on:
      condition: $TRAVIS_OS_NAME = linux
      tags: true
      branch: master
    provider: snap
    snap: ./app-builds/*.snap
    channel: candidate
    skip_cleanup: true
    # we use edge because of this: https://travis-ci.community/t/snap-deployment-stopped-working-out-of-nowhere/6908/2
    edge: true
  # Web deployment
  - on:
      condition: $TRAVIS_OS_NAME = linux
      tags: true
      branch: master
    provider: script
    script: sshpass -p "$DEPLOY_PASS" rsync -avz ./dist $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    skip_cleanup: true
# NOTE: disabled until next release of electron builder and until electron works with osx again
#  - on:
#      branch: master
#      condition: $TRAVIS_OS_NAME = osx
#      tags: true
#    provider: script
#    script: xcrun altool --upload-app -f app-builds/mas/superProductivity-*.pkg -u "${APPLEID}" -p "${APPLEIDPASS}"
#    skip_cleanup: true


# NOTE: this would only work, if we could and wanted to auto publish the github draft
#  - provider: script
#    script: brew update && brew install vitorgalvao/tiny-scripts/cask-repair && openssl aes-256-cbc -K $encrypted_c04542ca1075_key -iv $encrypted_c04542ca1075_iv -in build/hub.enc -out ~/.config/hub -d && cask-repair -b -v $TRAVIS_TAG superproductivity
#    skip_cleanup: true
#    on:
#      branch: master
#      condition: $TRAVIS_OS_NAME = osx
#      tags: true
